### ISSUE TITLE
deploy_compute() not working for Copied JSON from Jobs

### ISSUE THREAD

**Issue by mj-hope** [databricks-industry-solutions/anti-money-laundering#2]
Trying to use the function from RUNME notebook 
`NotebookSolutionCompanion().deploy_compute(job_json, run_job=run_job)`

Please refer to JSON Below

Initially it was giving out `KeyError` for `tasks` , So I took tasks Out of settings object.
It seems working fine, but name of the job turns to something like this - 
`[RUNNER] myemail@company.com | 888f49b63335eec0857d6359b68c4fd32f9fe5cd97489ce9989a29d534ec92a0`
Copied the JSON from Jobs>> view JSON

Any help would be much appreciated!

```
{
    "job_id": <>,
    "settings": {
        "name": "test_job",
        "email_notifications": {
            "on_start": [
                "<>"
            ],
            "on_success": [
                "<>"
            ],
            "on_failure": [
                "<>"
            ],
            "no_alert_for_skipped_runs": false
        },
        "timeout_seconds": 0,
        "schedule": {
            "quartz_cron_expression": "00 30 18 * * ?",
            "timezone_id": "Asia/Kolkata",
            "pause_status": "UNPAUSED"
        },
        "max_concurrent_runs": 1,
        "tasks": [
            {
                "task_key": "Execute_Notebook",
                "notebook_task": {
                    "notebook_path": "/release/baby_yoda",
                    "base_parameters": {
                        "source_storage_account": "<>"
                    },
                    "source": "WORKSPACE"
                },
                "existing_cluster_id": "<>",
                "timeout_seconds": 0,
                "email_notifications": {}
            }
        ],
        "format": "MULTI_TASK"
    }
}
```

**Comment by dbbnicole** [comment]
Hi @Mutthu99 : You should not need to update the job definition json if you are intending to use the content notebooks in this accelerator. 

If you would like to replicate the way automation is done to package your own pipeline, then try following the examples of RUNMEs in this and other repos in this Github Organization. Posting the json from an existing job is not expected to work, since we made some conscious changes to make the job json more resilient and multi-cloud friendly (using relative path of notebooks, embedding VM types for all 3 clouds).
